server:
  port: 8081
  #port: ${PORT:${SERVER_PORT:0}} # se utiliza esta linea en caso de querer puerto aleatorio y se comenta la del puerto fijo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USUARIO-SERVICE

  config:
    import: optional:configserver:http://CONGIF-SERVER #Se utiliza el optional: cuando se quiere utilizar el archivo por default del config server y no definir un perfil especifico
  #profiles: #se establece esta etiqueta para elegir el perfil de archivo de configuracion del config server
    #active: prod #se establece esta etiqueta para elegir el perfil de archivo de configuracion del config server